package workshop.demo.DTOs;

public enum Status {
   AUCTION_WON, AUCTION_LOSED, AUCTION_PENDING, BID_PENDING, BID_ACCEPTED, BID_REJECTED
      //  Rejected, Waiting, Accepted, END, AuctionPending, AUCTION_WON, AUCTION_LOSED, AUCTION_PENDING, BID_PENDING, BID_ACCEPTED, BID_REJECTED

}
